[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"